#*******************************************************************************
#Vendor: Xilinx 
#Associated Filename: sdaccel.mk
#Purpose: Makefile exmaple for SDAccel Compilation
#
#*******************************************************************************
#Copyright (C) 2015-2016 XILINX, Inc.
#
#This file contains confidential and proprietary information of Xilinx, Inc. and 
#is protected under U.S. and international copyright and other intellectual 
#property laws.
#
#DISCLAIMER
#This disclaimer is not a license and does not grant any rights to the materials 
#distributed herewith. Except as otherwise provided in a valid license issued to 
#you by Xilinx, and to the maximum extent permitted by applicable law: 
#(1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX 
#HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, 
#INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, OR 
#FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable (whether 
#in contract or tort, including negligence, or under any other theory of 
#liability) for any loss or damage of any kind or nature related to, arising under 
#or in connection with these materials, including for any direct, or any indirect, 
#special, incidental, or consequential loss or damage (including loss of data, 
#profits, goodwill, or any type of loss or damage suffered as a result of any 
#action brought by a third party) even if such damage or loss was reasonably 
#foreseeable or Xilinx had been advised of the possibility of the same.
#
#CRITICAL APPLICATIONS
#Xilinx products are not designed or intended to be fail-safe, or for use in any 
#application requiring fail-safe performance, such as life-support or safety 
#devices or systems, Class III medical devices, nuclear facilities, applications 
#related to the deployment of airbags, or any other applications that could lead 
#to death, personal injury, or severe property or environmental damage 
#(individually and collectively, "Critical Applications"). Customer assumes the 
#sole risk and liability of any use of Xilinx products in Critical Applications, 
#subject only to applicable laws and regulations governing limitations on product 
#liability. 
#
#THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT 
#ALL TIMES.
#
#******************************************************************************
ifndef XILINX_SDACCEL
$(error Environment variable XILINX_SDACCEL is required and should point to SDAccel install area)
endif

SDA_FLOW = cpu_emu
HOST_SRCS = cnn.cpp cnn_runall.cpp ../seq.cpp ../seq_cnn.cpp ocl_cnn.cpp ../xcl.cpp ../helper.cpp ../oclErrorCodes.cpp ../ModelImporter.cpp
HOST_EXE_DIR=.
HOST_EXE = cnn
HOST_CFLAGS = -g -std=c++0x -Wall -DFPGA_DEVICE -DC_KERNEL -I${XILINX_SDACCEL}/runtime/include/1_2 -I..
HOST_LFLAGS = -L${XILINX_SDACCEL}/runtime/lib/x86_64 -lxilinxopencl -llmx6.0

CLCC_JOBS = 8        # number of jobs for compile and synthesis
CLCC_OPT_LEVEL = -O3 # optimization level of the kernel source

KERNEL_SRCS = krnls_cnn.cl
//KERNEL_SRCS = emu_try.cl
KERNEL_NAME = 
KERNEL_DEFS = 
KERNEL_INCS = 

#set target device for XCLBIN
XDEVICE=xilinx:adm-pcie-ku3:2ddr:3.0
XDEVICE_REPO_PATH=
KEEP_TEMP=
KERNEL_DEBUG=1
XCLBIN_NAME=bin_cnn
HOST_CFLAGS+=-DTARGET_DEVICE=\"${XDEVICE}\"
#BOARD_SETUP_FILE needs to point to setup.sh generated by xbinst command
BOARD_SETUP_FILE=setup.sh

ifeq (${SDA_FLOW},cpu_emu)
    CLCC_OPT += -t sw_emu
    XCLBIN = ${XCLBIN_NAME}_cpu_emu.xclbin
else ifeq (${SDA_FLOW},hw_emu)
    CLCC_OPT += -t hw_emu
    XCLBIN = ${XCLBIN_NAME}_hw_emu.xclbin
else ifeq (${SDA_FLOW},hw)
    XCLBIN = ${XCLBIN_NAME}_hw.xclbin
    CLCC_OPT += -t hw
else
$(error No SDA_FLOW!)
endif

HOST_ARGS = ${XCLBIN} 

include ../../common/common.mk
